### ISSUE TITLE
Flash of desktop screen on laptop resume

### ISSUE THREAD

**Issue by ldelossa** [jovanlanik/gtklock#13]
Hey, 

`Gtklock` working pretty great for me. However, if I shut my laptop screen and allow it to suspend, when I come back, I get a flash of my desktop windows before `gtlock` renders itself. 

Here is my swayidle configuration:

```
exec swayidle -w \
         timeout 300   'gtklock -d -s ~/.config/gtklock/style.css' \
         timeout 600   'swaymsg "output * dpms off"' \
         resume        'swaymsg "output * dpms on"' \
         after-resume  'gtklock -d -s ~/.config/gtklock/style.css'
```

I did have that `after-resume` line as `before-sleep` at one point, but that failed to invoke `gtlock` all together.

**Comment by jovanlanik** [comment]
The flash is probably due to the delay between the laptop resuming and gtklock staring. I can't really do anything about that.

What I'm more worried about is the before-sleep option not working with gtklock. It led me to discover that on my system gtklock just exits if I suspend and resume the device while locked... What's worse is that I found this behaviour in all programs using gtk-layer-shell, but only when using multiple outputs. I want to test this on a different system but don't currently have one on hand. 

Maybe this is the same issue that you encountered? Do you have multiple outputs connected when this happens? Can you try starting gtklock by a method other than swayidle and see if it happens?

**Comment by ldelossa** [comment]
Hey @jovanlanik 

So I just did this test:
1) Killed swayidle in my current session
2) Plugged in dock so viewing multi-monitor.
3) Ran "gtklock" from the CLI directly
4) Hopped to new `tty` and forced suspend with `systemctl suspend`
5) Woke computer up, returned to `tty` with Sway. 

When I returned `gtklock` is still running and has kept the locked session, so I'm not exactly noticing this flaw you are. 

Also, oddly enough the desktop flash screen only occurs when I'm plugged into my dock with multi-monitors.

**Comment by jovanlanik** [comment]
Can you also try suspending while sway is still active (without changing to tty)?

1. run `$ sleep 5 && systemctl suspend'
2. then run gtklock

If I do it your way l, it doesn't happen to me either.

**Comment by ldelossa** [comment]
Tried your way, I still come back to gtklock. No crash.

**Comment by jovanlanik** [comment]
While multiple output are connected?

**Comment by ldelossa** [comment]
Yup. With multiple monitor outs.

**Comment by jovanlanik** [comment]
Well I'm confused... I absolutely do not understand why `before-sleep` doesn't work with gtklock. I'll have to do try installing elogind and try it for myself...
I also don't understand this problem with gtk-layer-shell but until I replicate it on a different system I'll assume it's specific to me.

**Comment by ldelossa** [comment]
Ill give it another go in a bit, but AFAICT, it lives over a suspend/resume

**Comment by jovanlanik** [comment]
I think I pinned down the issue I had as the same as or related to #6, so when I fix that I'll try replicating your issue.

**Comment by ldelossa** [comment]
Thanks, lookings promising.

**Comment by ldelossa** [comment]
I do, 

```
bindswitch --reload --locked lid:on output eDP-1 disable
bindswitch --reload --locked lid:off output eDP-1 enable
``` 
My laptop display.

**Comment by jovanlanik** [comment]
I fixed it in the latest commit but it requires some config:
1. If you use swayidle, lock using `before-sleep`: `$ swayidle -w before-sleep 'gtklock -d'. This way the window is created and rendered before sleep.
2. Avoid disabling outputs before sleep. In your config `bindswitch` disables eDP-1 even when going to sleep, this shouldn't happen because it destroys window and a new one is only created when the output gets enabled after resume. Unfortunately, I can't do anything else about it. It's a limitation of wlr-layer-shell, the window must close if you disable the output. You can still disable the output in situations where the lid doesn't put the device to sleep. Maybe you can check if the laptop is docked before disabling eDP-1 on `bindswitch`.

**Comment by ldelossa** [comment]
Hmm, AFA point 2 goes, my laptop will only sleep on lid closed if that setting is there. I tried it with a disable dpms setting as well, but that keeps the laptop awake .

**Comment by jovanlanik** [comment]
That's strange, I also use clamshell and my device sleeps regardless of sway settings. Maybe check `/etc/systemd/logind.conf`.

**Comment by ldelossa** [comment]
Okay let me double check.

**Comment by ldelossa** [comment]
May i ask, what are your lid shut settings?

**Comment by jovanlanik** [comment]
I use the defaults, so the entire file is commented out but I think these are the relevant values:
```
[Login]
HandleLidSwitch=suspend
HandleLidSwitchExternalPower=suspend
HandleLidSwitchDocked=ignore
LidSwitchIgnoreInhibited=yes

[Sleep]
AllowSuspend=yes
AllowSuspendInterrupts=no
BroadcastSuspendInterrupts=yes
``

**Comment by jovanlanik** [comment]
Oh, sorry. In my sway config I have:
```
exec_always exec sway-monitors.sh
bindswitch --locked lid:toggle exec exec sway-monitors.sh
```
And in the sway-monitors.sh script I check if the laptop is docked by connected devices:
```sh
#!/bin/sh

# Specific to my setup
docked() {
	lspci -n | grep -q '1002:67df' && return 0
	lsusb | grep -q '258a:0036' && return 0
	return 1
}

docked || exit

if grep -q open /proc/acpi/button/lid/LID/state
then
	swaymsg output eDP-1 enable
else
	swaymsg output eDP-1 disable
fi
```

**Comment by ldelossa** [comment]
Ohh nice example. Thanks a lot! Ill give this ago in a but

**Comment by jovanlanik** [comment]
The part that checks dock is really specific to my setup, so you might have to change it up a little...

**Comment by ldelossa** [comment]
Yup, ill find the Guids

**Comment by jovanlanik** [comment]
Now that I think about it, a better check would be checking the number of available outputs using swaymsg...

**Comment by jovanlanik** [comment]
I've had some problems with the script... When suspending, undocking and resuming the output would stay disabled. 
Updated script:
```sh
#!/bin/sh

# Specific to my setup
docked() {
	lspci -n | grep -q '1002:67df' && return 0
	lsusb | grep -q '258a:0036' && return 0
	return 1
}

if grep -q open /proc/acpi/button/lid/LID/state
then
	swaymsg output eDP-1 enable
else
	docked && swaymsg output eDP-1 disable
fi
```
Alternative docking function:
```sh
# More universal but depends on jq
docked() {
	[ "$(swaymsg -t get_outputs | jq '. | length')" -ne 1 ] && return 0
	return 1
}
```

**Comment by jovanlanik** [comment]
I'm closing this issue because it not currently (and as long as gtklock can't use ext-session-lock) possible to fix but can be mostly avoided by never disabling all outputs.
